### PR TITLE
Create Anurag-0-1-A.md

### PR DESCRIPTION
**Pull request by Anurag-0-1-A**

### CODE REVIEW

**Review by lasr21 — APPROVED** [review]
**Hola Anurag-0-1-A,**
**Estamos muy felcies de verte en Talent Land, vamos a revisar ese PR!**

Excelente, ahora estás a un paso de participar en la rifa de plaeras de GitHub. Encuentra un hubber o Campus Expert para que pueda aceptar tu Pull request y darte stickers de GitHub.

**Comment by Anurag-0-1-A** [comment]
Hola!!🙏@ultr4nerd , @lasr21 , @David-Lazaro-Fernandez ,

Would you please approve this pull request?☺️

**Comment by Anurag-0-1-A** [comment]
Thank you so much! @BubuDavid .😀
What's next now?

**Comment by Anurag-0-1-A** [comment]
What about Stickers and T-Shirt?😅

**Comment by BubuDavid** [comment]
Hi there @Anurag-0-1-A, this Repo was for an in-person event called Talent Land in México and we were doing the activities for in-person prizes like candies, stickers and photos. You are welcome to participate in next edition if you have the opportunity 😄 🚀

**Comment by Anurag-0-1-A** [comment]
Thanks for sharing😂
Hope to get them some other day😊

**Pull request merged**
